/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#12242E",
        card: "#1C2E38",
        "card-elevated": "#21384A",
        popover: "#1C2E38",
        sidebar: "#101F28",
        foreground: "#F3E3EA",
        "muted-foreground": "#E4A2B1",
        "subtle-foreground": "#9BB0BD",
        muted: "#24272B",
        input: "#20333D",
        border: "#324859",
        primary: "#FBE2A7",
        "primary-foreground": "#12242E",
        secondary: "#E4A2B1",
        accent: "#C67B96",
        ring: "#50AFB6",
        destructive: "#E35EA4",
        chart1: "#50AFB6",
        chart2: "#E4A2B1",
        chart3: "#C67B96",
        chart4: "#175C6C",
        chart5: "#24272B",
      },
      fontFamily: {
        serif: ["Lora_600SemiBold"],
        "serif-regular": ["Lora_400Regular"],
        sans: ["Poppins_400Regular"],
        "sans-medium": ["Poppins_500Medium"],
        "sans-semibold": ["Poppins_600SemiBold"],
        "sans-bold": ["Poppins_700Bold"],
      },
    },
  },
  plugins: [],
};
